app:
  init:
    stocks:
      - AAPL
      - MSFT
      - TSLA
      - NVDA


quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      enabled: false
    username: stockpilot
    password: stockpilot
    jdbc:
      url: jdbc:postgresql://localhost:15432/stockpilot

  hibernate-orm:
    # FÃ¼r Entwicklung: Schema automatisch anpassen, Daten bleiben erhalten
    database:
      generation: update